language: go

before_srcipt:
   - go version
install:
# 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.79.1/hugo_extended_0.79.1_Linux-64bit.tar.gz
  - tar -xzvf hugo_extended_0.79.1_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version

script:
# 运行hugo命令
  - hugo
# 指定的仓库地址
env:
 global:
    - CODING_REF: e.coding.net/blackhuose/blog.git
    
after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "update blog"
  - git remote  add origin https://19877550194:${CODING_TOKEN}@${CODING_REF}
  - git push --force --quiet origin master 